version: '3'

includes:
  _common:
    taskfile: ../repo-standards-kit/Taskfile.common.yml
    optional: true
    flatten: true
    dir: '.'
    vars:
      REPO_NAME: cli-wizard-core
      REPO_STANDARDS_KIT: ../repo-standards-kit
